.github/CODEOWNERS, README.md
- add  initial readme
- add codeowners file
=> Inital setup for mobile-android-logging

.github/workflows/merge_to_main.yml, .github/workflows/on_pull_request.yml, .github/workflows/on_push.yml, config/actions/setup-runner/action.yml, modules/api/build.gradle.kts
=> wip(workflows): Fix `merge_on_main` workflow

.github/workflows/merge_to_main.yml, .sh/getCurrentVersion, config/actions/maven-publish/action.yml, modules/buildLogic/plugins/src/main/kotlin/uk/gov/logging/extensions/ProjectExtensions.kt
Fix workflow to publish all `api`, `impl` and `testdouble` packages with correct versions
Resolves: DCMAW-8361
=> fix(publishing): Publish all packages

modules/testdouble/src/main/java/uk/gov/logging/testdouble/analytics/FakeAnalyticsLogger.kt
- add isDuplicateScreenView function
- Resolves: DCMAW-8361
- [] Successfully run changes on a testing device.
- [] ~~Complete automated Testing:~~
=> feat!: add isDuplicateScreenView function

.github/workflows/on_pull_request.yml
Ensuring builds pass this gate before being allowed to be merged
=> ci: adding sonar gate

config/actions/setup-runner/action.yml, docs/developerSetup/gradleManagedDevices.md, docs/developerSetup/runningTheCodeBase.md, modules/buildLogic/plugins/src/main/kotlin/uk/gov/logging/filetree/fetcher/AsmFileTreeFetcher.kt
- added fix missing to installing dependencies
- fixed listing issue caused by central change to One Login style guide
=> ci: update to fix failing builds

modules/api/build.gradle.kts, modules/impl/build.gradle.kts, modules/testdouble/build.gradle.kts
- Fix `verifyAarExistence` tasks for all modules
=> fix: Publishing pipeline

README.md, config/vale/styles/config/vocabularies/Base/accept.txt, modules/api/src/main/java/uk/gov/logging/api/CrashLogger.kt, modules/api/src/main/java/uk/gov/logging/api/Logger.kt, modules/api/src/main/java/uk/gov/logging/api/analytics/AnalyticsEvent.kt, modules/api/src/main/java/uk/gov/logging/api/analytics/extensions/ResourcesExtensions.kt
- Update README
- Add KDoc to:
- `AnalyticsEvent` methods
- `Logger` interface
- `CrashLogger` interface
- `ResourcesExtensions` methods
Resolves: DCMAW-9476
=> docs: Update documentation, README and KDoc

.github/workflows/merge_to_main.yml, .github/workflows/on_pull_request.yml
- update the pipelines dependency version to the latest:
`217b8fb9b8f5f1e763e8d56427d68180d422d62b` is the head of the main branch.
https://github.com/govuk-one-login/mobile-android-pipelines/commits/main/
Successful deployment build: 
https://github.com/govuk-one-login/mobile-android-logging/actions/runs/9714827052
=> ci: update build dependency

.github/workflows/on_pull_request.yml
Updated to ubuntu-24.04 runner to fix broken build.
=> ci: attempt run on newer runner to fix issues

build.gradle.kts
- [Ticket DCMAW-10478](https://govukverify.atlassian.net/browse/DCMAW-10478)
- Fixes breaking changes
- Project builds
[Sonar cloud report]: https://sonarcloud.io/project/overview?id=di-mobile-android-onelogin-app
=> fix: DCMAW-10478 Breaking Pipeline Change

modules/logging-api/src/main/java/uk/gov/logging/api/analytics/AnalyticsEvent.kt, modules/logging-api/src/main/java/uk/gov/logging/api/analytics/extensions/ResourcesExtensions.kt, modules/logging-api/src/test/java/uk/gov/logging/api/analytics/logging/MemorisedAnalyticsLoggerTest.kt, modules/logging-api/src/test/java/uk/gov/logging/api/analytics/parameters/FormResponseParametersTest.kt, modules/logging-api/src/test/java/uk/gov/logging/api/analytics/preferences/AnalyticsPrefsTest.kt, modules/logging-api/src/test/java/uk/gov/logging/api/analytics/preferences/StubAnalyticsPrefsTest.kt, modules/logging-testdouble/src/test/java/uk/gov/logging/testdouble/FakeCrashLoggerTest.kt, modules/logging-testdouble/src/test/java/uk/gov/logging/testdouble/analytics/FakeAnalyticsLoggerTest.kt
- Added `FakeAnalyticsLoggerTest`
-
=> test: Increase coverage

build.gradle.kts
- Update build.gradle.kts to include gradle extras as required by mobile-android-pipelines
- None
=> fix: DCMAW-10478 Breaking Changes

modules/logging-api/src/main/java/uk/gov/logging/api/analytics/parameters/data/TaxonomyLevel3.kt
- add Resume to TaxonomyLevel3
=> feat: add Resume to TaxonomyLevel3

modules/logging-api/src/main/java/uk/gov/logging/api/v3dot1/model/TrackEvent.kt, modules/logging-api/src/test/java/uk/gov/logging/api/v3dot1/model/ButtonTest.kt
**Description**
-  Amend `TrackEvent` for a button `type` to "submit form" (from `call to action`)
[Tutorial for writing good descriptions].
N/A
=> fix: Amend `TrackEvent` for a button `type` to "submit form"

modules/logging-api/src/main/java/uk/gov/logging/api/analytics/parameters/data/TaxonomyLevel3.kt
- add "document selection" to TaxonomyLevel3
[DCMAW-8054]: https://govukverify.atlassian.net/browse/DCMAW-8054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: DCMAW-8054 | Add Taxonomy for Document Selection

modules/logging-api/src/main/java/uk/gov/logging/api/analytics/parameters/data/TaxonomyLevel3.kt
- Taxonomy level 3 'licences' required, added here
=> feat: DCMAW-8827 - license taxonomy

.github/workflows/merge_to_main.yml, .github/workflows/on_pull_request.yml, Brewfile
- removed redundant cmd from Brewfile - no longer needed to be able to use cask
- removed redundant installations using cask which were specific to MacOS
=> build: Remove redundant dependencies from `Brewfile`

modules/logging-api/src/main/java/uk/gov/logging/api/analytics/parameters/data/TaxonomyLevel3.kt
- Add TaxonomyLevel3 INFORMATION, and OVERVIEW values required for wallet
- INFORMATION is required in [DCMAW-8118](https://govukverify.atlassian.net/browse/DCMAW-8118)
- OVERVIEW is required in [DCMAW-8119](https://govukverify.atlassian.net/browse/DCMAW-8119)
- None
[DCMAW-8118]: https://govukverify.atlassian.net/browse/DCMAW-8118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCMAW-8119]: https://govukverify.atlassian.net/browse/DCMAW-8119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: DCMAW 8117 GA4 analytics on Wallet Screen

modules/logging-api/src/main/java/uk/gov/logging/api/analytics/parameters/data/TaxonomyLevel3.kt, modules/logging-api/src/main/java/uk/gov/logging/api/analytics/parameters/data/Type.kt, modules/logging-api/src/main/java/uk/gov/logging/api/v3dot1/model/TrackEvent.kt, modules/logging-api/src/test/java/uk/gov/logging/api/v3dot1/model/FormTest.kt
- amend event to allow for custom implementation for the `TrackEvent.Form` and provide default the previous hard-coded value
- add new `Type` - `Toggle` for toggle
- add missing taxonomy level for BIOMETRICS_TOGGLE
- 
N/a
=> feat: Add new `Type` and amend `Form` event to allow custom Type

modules/logging-api/src/main/java/uk/gov/logging/api/analytics/parameters/data/TaxonomyLevel3.kt
N/A
[DCMAW-14145]: https://govukverify.atlassian.net/browse/DCMAW-14145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add TaxonomyLevel3 initialisation
